FROM ros:jazzy-ros-base
RUN apt update
RUN apt install -y vim
RUN apt install -y python3-pip
RUN apt install -y ros-jazzy-teleop-twist-keyboard
RUN apt install -y ros-jazzy-teleop-twist-joy
RUN apt install -y ros-jazzy-image-tools
RUN apt install -y ros-jazzy-compressed-image-transport
RUN apt install -y ros-jazzy-rviz2
RUN apt install -y ros-jazzy-rosbridge-server
RUN apt install -y ros-jazzy-web-video-server
RUN apt install -y ros-jazzy-nav2-bringup
RUN apt install -y ros-jazzy-image-publisher
WORKDIR /root/ros2_ws
