services:
  republisher:
    image: republisher
    network_mode: host
    ipc: host

  stereo_split_node:
    image: stereo_split_node
    network_mode: host
    ipc: host
    volumes:
      - ros2_config_20260403:/root/ros2_config

  stereo_proc:
    image: stereo_proc
    network_mode: host
    ipc: host

  camera_frame:
    image: camera_frame
    network_mode: host
    ipc: host

  joystick:
    image: joystick
    network_mode: host
    ipc: host
    volumes:
      - /dev:/dev
    device_cgroup_rules:
      - 'c 13:* rmw'

  nav2:
    image: nav2
    network_mode: host
    ipc: host
    volumes:
      - ros2_config_20260130:/root/ros2_config


volumes:
  ros2_config_20260403:
    external: true
  ros2_config_20260130:
    external: true
