services:
  republisher:
    image: republisher
    network_mode: host
    ipc: host

  stereo_split_node:
    image: stereo_split_node
    network_mode: host
    ipc: host
    volumes:
      - ros2_config_20260403:/root/ros2_config
    depends_on: [republisher]

  stereo_proc:
    image: stereo_proc
    network_mode: host
    ipc: host
    depends_on: [stereo_split_node]

  camera_frame:
    image: camera_frame
    network_mode: host
    ipc: host

  ffs:
    image: ros2_ffs
    network_mode: host
    ipc: host
    deploy:
      resources:
        reservations:
          devices:
            - driver: nvidia
              capabilities: [gpu]
    depends_on: [stereo_proc]

  joystick:
    image: joystick
    network_mode: host
    ipc: host
    volumes:
      - /dev:/dev
    device_cgroup_rules:
      - 'c 13:* rmw'

  nav2:
    image: nav2
    network_mode: host
    ipc: host
    volumes:
      - ros2_config_20260130:/root/ros2_config

  rviz2:
    image: rviz2
    network_mode: host
    ipc: host
    volumes:
      - type: bind
        source: $XAUTHORITY
        target: $XAUTHORITY
    environment:
      - XAUTHORITY=$XAUTHORITY
      - DISPLAY=$DISPLAY
    depends_on: [camera_frame]


volumes:
  ros2_config_20260403:
    external: true
  ros2_config_20260130:
    external: true
