services:
  motors:
    image: robot_thomas
    privileged: true
    network_mode: host

  camera:
    image: robot_camera
    privileged: true
    network_mode: host

  lidar:
    image: robot_lidar
    privileged: true
    network_mode: host
