services:
  motors:
    image: thomas
    privileged: true
    network_mode: host

  camera:
    image: camera
    privileged: true
    network_mode: host

  lidar:
    image: lidar
    privileged: true
    network_mode: host
