services:
  motors:
    image: thomas
    network_mode: host
    devices:
      - "/dev/spidev0.1"

  camera:
    image: camera
    network_mode: host
    volumes:
      - /dev:/dev
    device_cgroup_rules:
      - 'c 81:* rmw'

  lidar:
    image: lidar
    network_mode: host
    volumes:
      - /dev:/dev
    device_cgroup_rules:
      - 'c 188:* rmw'
